model:
  type: FINDER
  backbone:
    type: ActorCritic
    input_dim: 10
    hidden_dim: 64
    num_layers: 3
    num_critics: 2
    aggr: mean
    graph_aggr: add
    norm: layer
    dropout: 0.0
    use_residual: true
