model:
  type: FINDER
  backbone:
    type: ActorCritic
    input_dim: 10
    hidden_dim: 128
    num_layers: 2
    num_critics: 3
    aggr: mean
    graph_aggr: add
    norm: layer
    dropout: 0.1
    use_residual: true
